services:
  - type: web
    name: chronos-website
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: python startup_render.py
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chronos-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SITE_URL
        value: https://chronos-website.onrender.com
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: ChangeMe123!
      - key: EMAIL_HOST_USER
        value: "ilyas.khan.waytoweb@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "awne zyuo jotw ophx"
      - key: DEFAULT_FROM_EMAIL
        value: CHRONOS Luxury Watches <noreply@example.com>
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_SsJC0KFuJLu5dG"
      - key: RAZORPAY_KEY_SECRET
        value: "P8KzjJhIuMGWbhJn0jTU3OBZ"
      - key: SMS_PROVIDER
        value: email


databases:
  - name: chronos-db
    plan: free
